# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

input_number:
  light_temperature:
    name: Temperature
    min: 2000
    max: 6500
    initial: 2700
    step: 1

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
