# Load default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

# Load global variables
input_number: !include global_variables/input_number.yaml
input_select: !include global_variables/input_select.yaml

# Load automations
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
